name: Run Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[tests]'
          python -m nltk.downloader brown
      - name: Run tests
        run: |
          coverage run -m pytest -s
          coverage report -m
